name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-gazebo6'

jobs:
  focal-ci:
    runs-on: ubuntu-20.04
    name: Ubuntu Focal CI
    steps:
      - name: Run CI
        id: ci
        uses: azeey/action-gz-ci@focal_core_dump
  jammy-ci:
    runs-on: ubuntu-22.04
    name: Ubuntu Jammy CI
    steps:
      - name: Run CI
        id: ci
        uses: azeey/action-gz-ci@focal_core_dump
