name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-gazebo6'

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    container:
      image: ubuntu:focal
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install curl
        run: |
          apt update
          apt install -y curl
      - name: Download build script
        run: |
          curl -o build.sh https://raw.githubusercontent.com/azeey/action-gz-ci/focal_core_dump/entrypoint.sh
          chmod +x build.sh
      - name: Set cores to get stored in /cores
        run: |
          mkdir /cores
          chmod 777 /cores
          # Core filenames will be of the form executable.pid.timestamp:
          bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'
      - name: Compile and test
        id: ci
        run: |
          # Allow core dumps
          ulimit -c unlimited
          ./build.sh "" 1
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}  # Run only if something went wrong
        with:
          name: cores
          path: /cores
